version: '3.3'

volumes:
  data: # volume for mysql
  index: # volume for solr
  cache: # volume for composer and other tools

services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

  web:
    depends_on:
      - db
    image: brettt89/silverstripe-web:7.1-platform
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - type: volume
        source: ./cache
        target: /cache
      - type: tmpfs
        target: /tmp
      - type: volume
        source: index
        target: /index
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8002:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    depends_on:
      - db